# gratitude_phrases.py

# Define gratitude phrases for different sentiments
positive_phrases = [
    "I feel incredibly blessed to have such supportive friends in my life.",
    "Today, I truly appreciated the beauty of nature while walking through the park.",
    "Each moment spent with my family brings me immense joy and gratitude.",
    "Kindness from strangers never fails to warm my heart.",
    "Learning new things today has filled me with gratitude for the opportunities I have.",
    "Savoring a delicious meal reminded me of the abundance I have.",
    "I cherish the quiet moments of reflection that help me find peace.",
    "The laughter shared with friends today was truly uplifting.",
    "Receiving compliments boosts my confidence and fills me with appreciation.",
    "Having a warm cup of coffee in hand makes me grateful for small comforts.",
    "Every sunset I witness reminds me of the beauty in everyday life.",
    "I’m thankful for the chance to explore new hobbies that excite me.",
    "Helping others today brought me a sense of fulfillment.",
    "Today’s positive interactions with colleagues made my workday enjoyable.",
    "Finding a good book to read has reignited my passion for learning.",
    "I appreciate the guidance and wisdom of my mentors.",
    "The time spent volunteering today reminded me of the joy in giving back.",
    "I am grateful for the refreshing breeze that lifted my spirits.",
    "The small gestures of kindness I encountered today left a lasting impact.",
    "I enjoyed a wonderful conversation that brightened my day.",
    "Completing my goals for the week gives me a sense of accomplishment.",
    "Taking time to meditate has brought clarity to my thoughts.",
    "My pets' unconditional love fills my heart with gratitude.",
    "Experiencing different cultures through food has enriched my life.",
    "I feel thankful for the little surprises that life brings.",
    "The feeling of the sun on my face brings me pure happiness.",
    "Listening to my favorite songs uplifts my mood significantly.",
    "Today, I recognized the importance of self-care in my life.",
    "I’m thankful for the support of my community in tough times.",
    "Trying something new has brought excitement into my routine.",
    "Finding joy in the little things makes every day special.",
    "Reflecting on my achievements today makes me proud.",
    "The aroma of fresh flowers in my home brings a smile to my face.",
    "The beauty of the world around me fills me with wonder.",
    "Seeing a friend after a long time reminded me of our beautiful memories.",
    "Every act of kindness I witnessed today inspired me.",
    "Being part of a team that collaborates well makes work enjoyable.",
    "I appreciate the moments of laughter that break the monotony.",
    "Being able to express myself creatively is a true blessing.",
    "Today, I discovered a new favorite café that I can't wait to revisit.",
    "Sharing meals with loved ones creates cherished memories.",
    "The sense of adventure I feel when traveling is invigorating.",
    "Embracing change has opened up new possibilities for me.",
    "I am grateful for my health and the ability to move freely.",
    "Building new relationships has enriched my life.",
    "The kindness I see in others reminds me of the goodness in humanity.",
    "I cherish the lessons I learn from everyday experiences.",
    "Being in nature restores my spirit and brings me peace.",
    "Today’s challenges have helped me grow stronger and more resilient.",
    "Having access to knowledge through books and the internet is empowering.",
    "The warmth of a hug from a loved one is priceless.",
    "Witnessing acts of kindness reminds me to be grateful for the good in the world.",
    "I’m thankful for the creative ideas that flow freely when I’m inspired.",
    "The laughter of children brightens my day and fills my heart with joy.",
    "I appreciate the little moments of happiness that come my way.",
    "Finding a new passion project has sparked joy in my life.",
    "The encouragement I receive from others motivates me to keep going.",
    "The beauty of art brings a sense of wonder and appreciation.",
    "I am grateful for the opportunities to express my gratitude.",
    "The friendships I nurture fill my life with joy and laughter.",
    "Today, I took the time to enjoy my surroundings.",
    "I cherish the memories I create with those I love.",
    "Being part of meaningful conversations enriches my life.",
    "Each day, I strive to find the silver lining in every situation.",
    "The moments of quiet reflection allow me to recharge and appreciate life.",
    "The support I receive from my loved ones strengthens my spirit.",
    "I am thankful for the lessons learned through experience.",
    "Listening to the sounds of nature brings me peace.",
    "Each day offers a new chance to express my gratitude.",
    "I’m thankful for the small victories that motivate me.",
    "Connecting with others on a deeper level enriches my life.",
    "Today, I found beauty in the simplicity of everyday life.",
    "I appreciate the joy that comes from giving and receiving compliments.",
    "The thrill of trying something new invigorates my spirit.",
    "I am grateful for the little things that bring me happiness.",
    "Finding time for myself helps me recharge and feel appreciated.",
    "I enjoy the warmth of the sun on my skin.",
    "The sense of belonging I feel in my community is invaluable.",
    "I cherish the moments of stillness that allow me to reflect.",
    "Witnessing someone's success inspires me to pursue my goals.",
    "Today’s experiences have reminded me to be grateful for every moment.",
    "I appreciate the creativity that flows through my work.",
    "The smiles from strangers remind me of the goodness in humanity.",
    "I’m thankful for the opportunity to travel and explore new places.",
    "Finding joy in my daily routine has improved my outlook on life.",
    "The moments spent in laughter create lasting memories.",
    "I feel blessed to have people who uplift and support me.",
    "Each sunrise brings a fresh start and new opportunities.",
    "I cherish the time spent with my loved ones.",
    "Being open to new experiences brings excitement to my life.",
    "I appreciate the opportunities I have to grow and learn.",
    "Today’s moments of gratitude fill my heart with joy."
]


neutral_phrases = [
    "I had a decent meal today.",
    "The weather was average.",
    "I went for a walk in the park.",
    "Today was just another day.",
    "I completed my tasks for work.",
    "I enjoyed a nice cup of tea this afternoon.",
    "I read a book I found interesting.",
    "I watched a movie I had been curious about.",
    "I organized my workspace today.",
    "I chatted with a neighbor for a bit.",
    "I attended a meeting that went smoothly.",
    "I tried a new recipe and it turned out well.",
    "I listened to a podcast that I found engaging.",
    "I enjoyed some quiet time to reflect.",
    "I completed a workout routine I set for myself.",
    "I caught up with an old friend over the phone.",
    "I took time to rest and recharge today.",
    "I took a moment to enjoy my surroundings.",
    "I learned something new during my online course.",
    "I enjoyed the simplicity of my daily routine.",
    "I spent some time on a hobby I enjoy.",
    "I visited a local shop that had interesting items.",
    "I spent a few minutes meditating today.",
    "I enjoyed a simple breakfast that filled me up.",
    "I watched the clouds drift by in the sky.",
    "I took a few moments to breathe deeply and relax.",
    "I listened to calming music while I worked.",
    "I took care of some chores I had been putting off.",
    "I appreciated the comfort of my home today.",
    "I checked off a few items on my to-do list.",
    "I had a nice chat with a cashier while shopping.",
    "I completed a small project I've been working on.",
    "I took a moment to appreciate the colors of nature.",
    "I spent some time with my plants today.",
    "I enjoyed watching the birds at the feeder.",
    "I experienced a moment of clarity during my day.",
    "I found a good deal while shopping online.",
    "I took a moment to look out the window and reflect.",
    "I appreciated the convenience of technology today.",
    "I received a compliment from a colleague.",
    "I enjoyed browsing through a magazine.",
    "I felt content while sipping my coffee.",
    "I spent time reflecting on my goals.",
    "I appreciated the little things that brought me joy.",
    "I tried to be present in the moment today.",
    "I received some helpful advice from a friend.",
    "I spent some time organizing my digital files.",
    "I enjoyed the company of a familiar face today.",
    "I made a small improvement to my living space.",
    "I found a new app that I find useful.",
    "I watched a documentary that piqued my interest.",
    "I wrote down my thoughts in a journal.",
    "I took a moment to appreciate my surroundings.",
    "I shared a laugh with a coworker.",
    "I tried a new exercise and found it enjoyable.",
    "I found a moment of peace during a busy day.",
    "I caught up on some much-needed rest.",
    "I appreciated a moment of stillness in my day.",
    "I tried a different route on my daily walk.",
    "I found an interesting article to read online.",
    "I enjoyed the ambiance of a local café.",
    "I discovered a new favorite playlist.",
    "I took time to enjoy my favorite snack.",
    "I spent time reflecting on my week.",
    "I enjoyed a nice evening watching the sunset.",
    "I had a productive day at work.",
    "I appreciated the small joys of everyday life.",
    "I watched a show that made me smile.",
    "I learned a few new things from my colleagues.",
    "I appreciated the calmness of my surroundings.",
    "I took time to relax and recharge.",
    "I enjoyed the comfort of my favorite chair.",
    "I savored a delicious dessert I treated myself to.",
    "I took part in a community event.",
    "I received positive feedback on my work.",
    "I spent some time outdoors enjoying the fresh air.",
    "I appreciated the beauty of a simple flower.",
    "I attended a webinar that was informative.",
    "I made time for a hobby I've been neglecting.",
    "I appreciated the time I spent with family.",
    "I enjoyed a moment of silence during my day.",
    "I tried a new café in my neighborhood.",
    "I took a moment to appreciate the little things.",
    "I read some interesting news articles.",
    "I felt proud of my small achievements today.",
    "I made a plan for the week ahead.",
    "I discovered a new skill I want to learn.",
    "I spent some time in quiet contemplation.",
    "I took a moment to stretch and relax.",
    "I found comfort in a familiar routine.",
    "I watched a TED talk that inspired me.",
    "I appreciated the simple pleasure of a warm bath.",
    "I spent time thinking about my future.",
    "I enjoyed the process of tidying up.",
    "I felt a sense of calm during my day.",
    "I organized my thoughts through writing.",
    "I celebrated a small victory at work."
]

negative_phrases = [
    "I faced a lot of challenges this week that tested my patience.",
    "It was disappointing to miss out on an opportunity I was excited about.",
    "Today was tough, and I felt overwhelmed with my responsibilities.",
    "Struggling with self-doubt has been a recurring theme for me lately.",
    "I felt frustration due to miscommunication at work today.",
    "Not achieving my goals this week left me feeling disheartened.",
    "I encountered difficulties that made me question my abilities.",
    "Today’s setbacks taught me valuable lessons, even if they were hard to bear.",
    "Feeling exhausted after a long week has made it difficult to stay positive.",
    "I felt a bit lost when things didn’t go according to plan.",
    "Lack of motivation made today feel like a struggle.",
    "Today’s failures reminded me of my limitations.",
    "I found it hard to cope with the pressures of daily life.",
    "Experiencing conflict in relationships left me feeling unsettled.",
    "Today was filled with frustrations that tested my resilience.",
    "The stress of my workload is becoming overwhelming.",
    "I faced setbacks that challenged my perseverance.",
    "Feeling anxious about my future has been weighing on my mind.",
    "I struggled with feelings of disappointment and sadness today.",
    "The challenges I encountered made me question my choices.",
    "Today’s obstacles taught me the importance of patience.",
    "I felt overwhelmed by responsibilities that seemed unmanageable.",
    "Experiencing setbacks in my plans left me feeling disheartened.",
    "I found it difficult to stay optimistic amidst the chaos.",
    "The lack of communication in my team has caused frustration.",
    "I faced moments of doubt that made it hard to see the positives.",
    "Navigating difficult emotions today was a challenge.",
    "I felt the burden of expectations weighing heavily on me.",
    "Encountering negativity from others impacted my mood today.",
    "I struggled with feelings of inadequacy during the meeting.",
    "Today’s disappointments made me reflect on my choices.",
    "Facing criticism from others left me feeling vulnerable.",
    "I felt frustrated by the lack of support in my projects.",
    "The uncertainty of my situation created a sense of unease.",
    "I faced challenges that made me question my decisions.",
    "Feeling overwhelmed by my workload made today feel long.",
    "The stress of daily life has been tough to manage.",
    "Today’s struggles reminded me that it’s okay to ask for help.",
    "I encountered obstacles that tested my determination.",
    "Feeling discouraged by setbacks has been a common theme lately.",
    "Today was filled with moments of frustration and doubt.",
    "I faced challenges that made me feel isolated.",
    "The pressure to succeed can be exhausting at times.",
    "Experiencing negativity from others has affected my outlook.",
    "I struggled with feeling overwhelmed by my responsibilities.",
    "Today, I learned that it’s okay to take a step back.",
    "The obstacles I faced today taught me resilience.",
    "I felt disheartened by setbacks that impacted my progress.",
    "Dealing with difficult emotions can be draining.",
    "I found it hard to stay focused amidst distractions today.",
    "Facing rejection left me feeling vulnerable.",
    "I struggled to find the motivation to push through today.",
    "Today’s challenges tested my patience and perseverance.",
    "The stress of my responsibilities has been weighing on me.",
    "I faced difficulties that made me question my path.",
    "Feeling overwhelmed by the pace of life can be tough.",
    "I encountered moments of frustration that made me reflect.",
    "Navigating my emotions today felt like a rollercoaster.",
    "I felt burdened by expectations that seemed unrealistic.",
    "Experiencing moments of self-doubt has been common lately.",
    "Today was filled with frustrations that tested my resolve.",
    "I found it difficult to cope with unexpected challenges.",
    "The pressure of deadlines has been overwhelming.",
    "I felt disillusioned by setbacks that disrupted my plans.",
    "Facing challenges can sometimes feel isolating.",
    "I struggled with feelings of disappointment today.",
    "The negativity around me affected my mood.",
    "I faced challenges that made it hard to stay optimistic.",
    "Today was a reminder that setbacks are a part of life.",
    "Feeling overwhelmed by emotions can be exhausting.",
    "I encountered obstacles that tested my resilience.",
    "The burden of expectations has been hard to manage.",
    "Experiencing moments of frustration made me reflect.",
    "I struggled to maintain my motivation in tough times.",
    "Today’s difficulties taught me to appreciate the small victories.",
    "Facing challenges can help us grow, even when it’s tough.",
    "I felt disheartened by moments of doubt and uncertainty.",
    "The weight of my responsibilities felt heavy today.",
    "I encountered setbacks that challenged my perseverance.",
    "Feeling overwhelmed by life’s demands has been difficult.",
    "I found it hard to see the positives amidst frustrations.",
    "Today’s challenges reminded me of the importance of self-care.",
    "Navigating through tough emotions can be a journey.",
    "I struggled with feelings of inadequacy in my work.",
    "The stress of daily life can be overwhelming at times.",
    "I faced challenges that tested my resolve and strength.",
    "Experiencing setbacks can sometimes feel disheartening.",
    "Today reminded me that it’s okay to acknowledge my struggles.",
    "I found it difficult to stay grounded amidst the chaos.",
    "Feeling isolated during tough times can be tough."
]

